resolver: lts-19.33
packages:
  - dhall
  - dhall-bash
  - dhall-csv
  - dhall-docs
  - dhall-json
  - dhall-lsp-server
  - dhall-nix
  - dhall-openapi
  - dhall-toml
  - dhall-yaml
extra-deps:
  - github: haskell-nix/hnix
    commit: 2adbc502e62e755ca0372c913e6278ebe564d7d2
  - hnix-store-core-0.6.1.0
  - hnix-store-remote-0.6.0.0
  - tomland-1.3.3.2
  - validation-selective-0.1.0.2
nix:
  packages:
    - ncurses
    - zlib
flags:
  # https://github.com/RyanGlScott/mintty/issues/4
  mintty:
    Win32-2-13-1: false
