resolver: lts-18.28
packages:
  - dhall
  - dhall-bash
  - dhall-csv
  - dhall-docs
  - dhall-json
  - dhall-lsp-server
  - dhall-nix
  - dhall-openapi
  - dhall-toml
  - dhall-yaml
extra-deps:
  - co-log-core-0.3.2.0
  - hnix-0.16.0
  - hnix-store-core-0.5.0.0
  - hnix-store-remote-0.5.0.0
  - lsp-1.5.0.0
  - lsp-types-1.5.0.0
  - lsp-test-0.14.1.0
  - lucid-2.11.0
  - relude-1.0.0.1@sha256:35bcdaf14018e79f11e712b0e2314c1aac79976f28f4adc179985457493557d5,11569
  - semialign-1.2@sha256:9afb6eb7e50db7ca34d7c4108aec0f643dae2caaaa80394b44ffdd643315685c,2721
  - text-rope-0.2
  - typerep-map-0.5.0.0
nix:
  packages:
    - ncurses
    - zlib
flags:
  # https://github.com/RyanGlScott/mintty/issues/4
  mintty:
    Win32-2-13-1: false
